# Generated by Django 3.2.4 on 2021-06-08 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_auto_20210608_1123'),
        ('question', '0002_auto_20210608_1123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChoiceOptions',
        ),
        migrations.AddField(
            model_name='comprehensionchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.comprehensionquestion'),
        ),
        migrations.AddField(
            model_name='attentionchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.attentioncheckquestion'),
        ),
    ]
