# Generated by Django 3.2.4 on 2021-07-10 15:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.CharField(max_length=200, unique=True)),
                ('attention_all_attempted', models.BooleanField(default=False)),
                ('attention_passed', models.BooleanField(default=False)),
                ('comprehension_all_attempted', models.BooleanField(default=False)),
                ('comprehension_passed', models.BooleanField(default=False)),
                ('type_work', models.IntegerField(default=-1)),
                ('dssProposerAllocation', models.IntegerField(default=-1)),
                ('belief_elicitation', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=-1), default=list, size=None), default=list, size=None)),
                ('belief_elicitation_attempted', models.BooleanField(default=False)),
                ('approach_decision', models.IntegerField(default=-1)),
                ('minimum_offer', models.IntegerField(default=-1)),
                ('decision_and_minoffer_submitted', models.BooleanField(default=False)),
                ('postexperimental_submitted', models.BooleanField(default=False)),
                ('attention_responses', models.ManyToManyField(blank=True, to='question.AttentionChoice')),
                ('comprehension_responses', models.ManyToManyField(blank=True, to='question.ComprehensionChoice')),
                ('postexperimental_responses', models.ManyToManyField(blank=True, to='question.PostExperimentalChoice')),
            ],
        ),
    ]
