# Generated by Django 3.2.4 on 2021-08-19 17:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.CharField(max_length=200, unique=True)),
                ('comprehension_all_attempted', models.BooleanField(default=False)),
                ('comprehension_failed_times', models.IntegerField(default=0)),
                ('comprehension_passed', models.BooleanField(default=False)),
                ('type_work', models.IntegerField(default=-1)),
                ('comprehension_belief_all_attempted', models.BooleanField(default=False)),
                ('comprehension_belief_failed_times', models.IntegerField(default=0)),
                ('comprehension_belief_passed', models.BooleanField(default=False)),
                ('belief_elicitation', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=-1), default=list, size=None), default=list, size=None)),
                ('belief_elicitation_attempted', models.BooleanField(default=False)),
                ('proposer_type', models.IntegerField(default=-1)),
                ('proposer_offer', models.IntegerField(default=-1)),
                ('trust_automation', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=-1), default=list, size=None)),
                ('do_responders_consider_dss_while_deciding_proposers', models.BooleanField(default=False)),
                ('which_proposer_you_would_choose_to_be', models.IntegerField(default=-1)),
                ('if_resp_which_proposer_would_you_approach', models.IntegerField(default=-1)),
                ('proposer_most_responders_approach', models.IntegerField(default=-1)),
                ('i_think_responders', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=-1), default=list, size=None)),
                ('sex', models.CharField(blank=True, max_length=10)),
                ('age', models.IntegerField(default=1)),
                ('employment_status', models.CharField(blank=True, max_length=100)),
                ('highest_degree', models.CharField(blank=True, max_length=100)),
                ('survey_submitted', models.BooleanField(default=False)),
                ('unique_code', models.CharField(blank=True, editable=False, max_length=300)),
                ('unique_code_generated', models.BooleanField(default=False)),
                ('comprehension_belief_responses', models.ManyToManyField(blank=True, to='question.ComprehensionBeliefChoice')),
                ('comprehension_responses', models.ManyToManyField(blank=True, to='question.ComprehensionChoice')),
            ],
        ),
    ]
