# Generated by Django 3.2.4 on 2021-06-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20210608_1123'),
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='responses',
        ),
        migrations.AddField(
            model_name='worker',
            name='attention_check_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worker',
            name='attention_responses',
            field=models.ManyToManyField(to='question.AttentionChoice'),
        ),
        migrations.AddField(
            model_name='worker',
            name='comprehension_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worker',
            name='comprehension_responses',
            field=models.ManyToManyField(to='question.ComprehensionChoice'),
        ),
        migrations.AddField(
            model_name='worker',
            name='type_work',
            field=models.IntegerField(default=-1),
        ),
    ]
