# Generated by Django 3.2.4 on 2021-07-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='unique_code',
            field=models.CharField(blank=True, editable=False, max_length=300, unique=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='unique_code_generated',
            field=models.BooleanField(default=False),
        ),
    ]
