# Generated by Django 3.2.4 on 2021-07-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_auto_20210718_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='unique_code',
            field=models.CharField(blank=True, editable=False, max_length=300),
        ),
    ]
