# Generated by Django 3.2.4 on 2021-06-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_questionnaire'),
        ('worker', '0002_auto_20210608_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='attention_check_done',
            new_name='attention_all_attempted',
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='comprehension_done',
            new_name='attention_passed',
        ),
        migrations.AddField(
            model_name='worker',
            name='comprehension_all_attempted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worker',
            name='comprehension_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='worker',
            name='attention_responses',
            field=models.ManyToManyField(blank=True, to='question.AttentionChoice'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='comprehension_responses',
            field=models.ManyToManyField(blank=True, to='question.ComprehensionChoice'),
        ),
    ]
