# Generated by Django 3.2.4 on 2021-07-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_comprehensionbeliefchoice_comprehensionbeliefquestion'),
        ('worker', '0003_alter_worker_unique_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='comprehension_belief_all_attempted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worker',
            name='comprehension_belief_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worker',
            name='comprehension_belief_responses',
            field=models.ManyToManyField(blank=True, to='question.ComprehensionBeliefChoice'),
        ),
    ]
