# Generated by Django 3.2.4 on 2021-07-23 15:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0004_auto_20210723_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='postexperimental_responses',
        ),
        migrations.AddField(
            model_name='worker',
            name='attention_postexp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worker',
            name='autonomousagent_postexp',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=-1), default=list, size=None),
        ),
        migrations.AddField(
            model_name='worker',
            name='dss_postexp',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=-1), default=list, size=None),
        ),
        migrations.AddField(
            model_name='worker',
            name='most_responders_bargain_with_postexp',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=-1), default=list, size=None),
        ),
        migrations.AddField(
            model_name='worker',
            name='personality_postexp',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=-1), default=list, size=None),
        ),
        migrations.AddField(
            model_name='worker',
            name='unfair_postexp',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=-1), default=list, size=None),
        ),
    ]
