# Generated by Django 3.2.4 on 2021-07-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0005_auto_20210723_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='reason_approach_postexp',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='rethink_approach_postexp',
            field=models.IntegerField(default=-1),
        ),
    ]
