# Generated by Django 3.2.4 on 2021-07-23 20:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0006_auto_20210723_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='age',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='worker',
            name='employment_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='worker',
            name='highest_degree',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='worker',
            name='negative_reciprocity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=-1), default=list, size=None),
        ),
        migrations.AddField(
            model_name='worker',
            name='sex',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='worker',
            name='survey_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
