# Generated by Django 3.2.4 on 2021-07-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0007_auto_20210724_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='comprehension_failed_times',
            field=models.IntegerField(default=0),
        ),
    ]
