# Generated by Django 3.2.4 on 2021-07-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0008_worker_comprehension_failed_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='comprehension_belief_failed_times',
            field=models.IntegerField(default=0),
        ),
    ]
