# Generated by Django 3.2.4 on 2021-07-25 14:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0008_alter_worker_most_responders_bargain_with_postexp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='most_responders_bargain_with_postexp',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=-1), default=list, size=None),
        ),
    ]
