# Generated by Django 3.2.4 on 2021-07-25 23:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0009_worker_comprehension_belief_failed_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='svo_selected_indices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=-1), default=list, size=None),
        ),
    ]
